### ISSUE TITLE
Importing a json file via import is not possible without a bundler

### ISSUE THREAD

**Issue by ricklancee** [lifelynl/lifely-react-i18n#1]
In the examples and readme importing a json file via `import en from 'en.json'` is not possible with es2015 modules without some bundler like webpack. This might be confusing for people not using a json loader. It might be better to remove this from readme and examples. 

Example:
```js
import { configure } from 'lifely-react-i18n';

const en = {
    hello: {
      world: "Hello world"
    }
};

const nl = {
    hello: {
      world: "Hallo wereld"
    }
};

configure({
    defaultLanguage: 'nl',
    ...
```

**Comment by jessedvrs** [comment]
@ricklancee importing json files is actually possible with es2015 modules, by design
(because JSON is JavaScript Object Notation)

**Comment by jessedvrs** [comment]
The issue actually is:
`import en from 'en.json'` -> `import en from './en.json'`

**Comment by ricklancee** [comment]
Just realised my mistake 🙈
